### ISSUE TITLE
tenho uma reclamação

### ISSUE THREAD

**Issue by geovaniorsoli** [vidacalura/Jeek-online#6]
tem um problema que eu sou muito ruim

**Comment by vidacalura** [comment]
Olá Berg, infelizmente, não sou capaz de ajudar com isso. Porém, caso você continue jogando e treinando bastante, usando os modos de análise e o novo explorador de aberturas, acredito que você possa melhorar e se tornar um jogador muito forte com algum tempo. Estarei à disposição para ajudar como possível, e espero grandes coisas de você.

Um forte abraço,
vidacalura, desenvolvedor do Jeek Online

**Comment by geovaniorsoli** [comment]
Grato pela sua resposta.
